name: Vanish
main: ErkamKahriman\Vanish
version: 1.1
author: ErkamKahriman
api: 3.0.1
commands:
  vanish:
    description: "Vanish your self"
    aliases: [Vanish]
permissions:
  vanish.use:
    description: "Vanish use perm"
    default: op