name: Vanish
main: Erkam246\Vanish\Vanish
api: 3.0.0
version: "3.0"
author: ErkamKahriman
commands:
  vanish:
    description: "Vanish yourself"
    permission: "vanish.use"
permissions:
  vanish.use:
    description: "Vanish use perm"
    default: op