name: Vanish
main: ErkamKahriman\Vanish
version: 1.2
author: ErkamKahriman
api: 3.0.1
commands:
  vanish:
    description: "Vanish yourself"
permissions:
  vanish.use:
    description: "Vanish use permission"
    default: op